name: Shell Comands

on: [push]

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: Install xcodeproj ruby gem
        run: sudo gem install xcodeproj
      - name: Install python six package
        run: pip install six
      - name: Install NativeScript
        run: npm i -g nativescript
      - name: Restart bash
        run: exec bash
      # - name: Check if NativeScript is configured properly
      #  run: tns doctor
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install node packages
        run: npm i
      - name: Create directory nativescript-internal-plugin
        run: mkdir ../nativescript-internal-plugin
      - name: Test NativeScript
        run: tns test ios
      - name: List NativeScript devices
        run: tns device
