name: Shell Comands

on: [push]

jobs:
  run-shell-command:
    runs-on: macos-latest
    steps:
      - name: Install xcodeproj ruby gem
        run: sudo gem install xcodeproj
      - name: Install python six package
        run: pip install six
      - name: Finally install NativeScript
        run: npm i -g nativescript
      - name: Restart bash
        run: exec bash
      - name: Check if NativeScript is configured properly
        run: tns doctor
      # - name: checkout repo
      #   uses: actions/checkout@v3
      # - name: npm install
      #   run: npm i
      - name: List NativeScript devices
        run: tns device
